### PR TITLE
Ethnicity graduated resize

### PR DESCRIPTION
**Pull request by andrewmartini**
graduated ethn. layers updated and simplified

### CODE REVIEW

**Comment by ashron24** [comment]
great-- did you execute this pull, or do I need to confirm it?

**Comment by andrewmartini** [comment]
Its all done.  (since you made me a collaborator, I can accept my own pull
requests)

On Thu, Oct 8, 2015 at 12:00 PM, ashron24 notifications@github.com wrote:

> great-- did you execute this pull, or do I need to confirm it?
> 
> On Thu, Oct 8, 2015 at 10:23 AM, Andrew Martini notifications@github.com
> wrote:
> 
> > Merged #4 https://github.com/ashron24/cau-clergy-10-1-15/pull/4.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ashron24/cau-clergy-10-1-15/pull/4#event-430365774.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ashron24/cau-clergy-10-1-15/pull/4#issuecomment-146592538
> .

## 

Andrew Martini
718-473-4317
Twitter https://twitter.com/AndrewMartini3 | LinkedIn
http://www.linkedin.com/pub/andrew-martini/45/917/862

**Comment by ashron24** [comment]
ok great, thanks. ok for me to more the tract13 layer into one of the carto
accounts, and change the references to 'tract12' in the html to 'tract13'?

**Comment by andrewmartini** [comment]
Yeah shouldn't be a problem, (as long as all the column names are
identical).  I assume you are just replacing tract12 with tract13, and not
adding a 2012 comparison?
- Andrew

On Thu, Oct 8, 2015 at 1:22 PM, ashron24 notifications@github.com wrote:

> ok great, thanks. ok for me to more the tract13 layer into one of the carto
> accounts, and change the references to 'tract12' in the html to 'tract13'?
> 
> On Thu, Oct 8, 2015 at 1:12 PM, Andrew Martini notifications@github.com
> wrote:
> 
> > Its all done. (since you made me a collaborator, I can accept my own pull
> > requests)
> > 
> > On Thu, Oct 8, 2015 at 12:00 PM, ashron24 notifications@github.com
> > wrote:
> > 
> > > great-- did you execute this pull, or do I need to confirm it?
> > > 
> > > On Thu, Oct 8, 2015 at 10:23 AM, Andrew Martini <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Merged #4 https://github.com/ashron24/cau-clergy-10-1-15/pull/4.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/ashron24/cau-clergy-10-1-15/pull/4#event-430365774
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/ashron24/cau-clergy-10-1-15/pull/4#issuecomment-146592538
> > 
> > > .
> > 
> > ## 
> > 
> > Andrew Martini
> > 718-473-4317
> > Twitter https://twitter.com/AndrewMartini3 | LinkedIn
> > http://www.linkedin.com/pub/andrew-martini/45/917/862
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ashron24/cau-clergy-10-1-15/pull/4#issuecomment-146626947
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ashron24/cau-clergy-10-1-15/pull/4#issuecomment-146629870
> .

## 

Andrew Martini
718-473-4317
Twitter https://twitter.com/AndrewMartini3 | LinkedIn
http://www.linkedin.com/pub/andrew-martini/45/917/862

**Comment by andrewmartini** [comment]
FYI - i had made the demographic layer names include a year, so you would
have to update that as well if you are planning on sticking to one year.
(for example percent_white_12  or pakistani_gradu_12)

On Thu, Oct 8, 2015 at 1:40 PM, Andrew Martini andrewmartini333@gmail.com
wrote:

> Yeah shouldn't be a problem, (as long as all the column names are
> identical).  I assume you are just replacing tract12 with tract13, and not
> adding a 2012 comparison?
> - Andrew
> 
> On Thu, Oct 8, 2015 at 1:22 PM, ashron24 notifications@github.com wrote:
> 
> > ok great, thanks. ok for me to more the tract13 layer into one of the
> > carto
> > accounts, and change the references to 'tract12' in the html to 'tract13'?
> > 
> > On Thu, Oct 8, 2015 at 1:12 PM, Andrew Martini notifications@github.com
> > wrote:
> > 
> > > Its all done. (since you made me a collaborator, I can accept my own
> > > pull
> > > requests)
> > > 
> > > On Thu, Oct 8, 2015 at 12:00 PM, ashron24 notifications@github.com
> > > wrote:
> > > 
> > > > great-- did you execute this pull, or do I need to confirm it?
> > > > 
> > > > On Thu, Oct 8, 2015 at 10:23 AM, Andrew Martini <
> > > > notifications@github.com>
> > > > wrote:
> > > > 
> > > > > Merged #4 https://github.com/ashron24/cau-clergy-10-1-15/pull/4.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > > https://github.com/ashron24/cau-clergy-10-1-15/pull/4#event-430365774
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > 
> > > https://github.com/ashron24/cau-clergy-10-1-15/pull/4#issuecomment-146592538
> > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Andrew Martini
> > > 718-473-4317
> > > Twitter https://twitter.com/AndrewMartini3 | LinkedIn
> > > http://www.linkedin.com/pub/andrew-martini/45/917/862
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/ashron24/cau-clergy-10-1-15/pull/4#issuecomment-146626947
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ashron24/cau-clergy-10-1-15/pull/4#issuecomment-146629870
> > .
> 
> ## 
> 
> Andrew Martini
> 718-473-4317
> Twitter https://twitter.com/AndrewMartini3 | LinkedIn
> http://www.linkedin.com/pub/andrew-martini/45/917/862

## 

Andrew Martini
718-473-4317
Twitter https://twitter.com/AndrewMartini3 | LinkedIn
http://www.linkedin.com/pub/andrew-martini/45/917/862

**Pull request merged**
